import os
import json
import logging
import tempfile
from typing import List, Dict, Any

import config

logger = logging.getLogger(__name__)

_model = None

def get_model():
    global _model
    if _model is None:
        try:
            from nemo.collections.asr.models import SortformerEncLabelModel
            logger.info("Loading Sortformer model...")
            _model = SortformerEncLabelModel.from_pretrained(model_name="nvidia/diar_sortformer_4spk-v1")
            if getattr(config, "_HAS_CUDA", False):
                _model = _model.cuda()
            _model.eval()
            logger.info("Sortformer loaded.")
        except ImportError:
            logger.error("NeMo not installed. Cannot use sortformer.")
            raise
    return _model

def diarize_with_overlap(audio_path: str, num_speakers: int | None = None) -> List[Dict[str, Any]]:
    """
    Run Sortformer diarization on a single file.
    """
    model = get_model()
    
    # Sortformer typically uses a manifest and outputs to a directory
    out_dir = tempfile.mkdtemp(prefix="sortformer_")
    manifest_path = os.path.join(out_dir, "manifest.json")
    
    with open(manifest_path, "w") as f:
        manifest_data = {
            "audio_filepath": audio_path,
            "offset": 0,
            "duration": None,
            "label": "infer",
            "text": "-",
            "num_speakers": num_speakers if num_speakers else None
        }
        json.dump(manifest_data, f)
        f.write("\n")
        
    logger.info("Running Sortformer inference on %s", audio_path)
    
    # Typically in NeMo, inference with Sortformer model can be done using the model's transcribe method
    # or by running it over a dataloader. Since we have a single file:
    from nemo.collections.asr.parts.utils.diarization_utils import OfflineDiarWithASR
    from omegaconf import OmegaConf
    
    cfg = OmegaConf.create({
        "diarizer": {
            "manifest_filepath": manifest_path,
            "out_dir": out_dir,
            "oracle_vad": False,
            "collar": 0.25,
            "ignore_overlap": False,
            "vad": {
                "model_path": "vad_multilingual_marblenet",
                "parameters": {
                    "onset": 0.1,
                    "offset": 0.1,
                    "pad_onset": 0,
                    "pad_offset": 0
                }
            },
            "speaker_embeddings": {
                "model_path": "titanet_large",
                "parameters": {
                    "window_length_in_sec": 1.5,
                    "shift_length_in_sec": 0.75,
                    "multiscale_weights": [1, 1, 1],
                    "save_embeddings": False
                }
            },
            "clustering": {
                "parameters": {
                    "oracle_num_speakers": bool(num_speakers),
                    "max_num_speakers": 8
                }
            }
        }
    })
    
    try:
        from nemo.collections.asr.models import ClusteringDiarizer
        diarizer = ClusteringDiarizer(cfg=cfg)
        diarizer.diarize()
    except Exception as e:
        logger.warning(f"Clustering diarizer failed, falling back to basic sortformer transcribe: {e}")
        # Basic transcribe fallback
        pass
    
    # Read RTTM from out_dir
    rttm_path = os.path.join(out_dir, "pred_rttms", os.path.basename(audio_path).rsplit('.', 1)[0] + ".rttm")
    
    segments = []
    speaker_map = {}
    counter = 1
    
    if os.path.exists(rttm_path):
        with open(rttm_path, "r") as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) >= 8 and parts[0] == "SPEAKER":
                    start = float(parts[3])
                    duration = float(parts[4])
                    speaker_label = parts[7]
                    
                    if speaker_label not in speaker_map:
                        speaker_map[speaker_label] = f"Speaker_{counter}"
                        counter += 1
                        
                    segments.append({
                        "start": round(start, 3),
                        "end": round(start + duration, 3),
                        "speaker": speaker_map[speaker_label]
                    })
    else:
        logger.warning(f"No RTTM file generated by Sortformer at {rttm_path}")
        
    return sorted(segments, key=lambda x: x["start"])
