server {
    listen 80;
    client_max_body_size 600M;

    location / {
        proxy_pass http://api:8009;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 600s;
    }
}
